In [15]:
import pandas as pd
import os

In [6]:
data_path = r"C:\Users\kanam\OneDrive\Desktop\jb\data\delivery_events.csv"

In [7]:
df = pd.read_csv(data_path)

In [9]:
df.head()

,event_id,load_id,trip_id,event_type,facility_id,scheduled_datetime,actual_datetime,detention_minutes,on_time_flag,location_city,location_state
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55.918185,0,False,Houston,TX
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,MI
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26.608430,62,True,Kansas City,MO
3,EVT00000004,LOAD00000002,TRIP00000002,Delivery,FAC00050,2022-01-02 02:13:26.608430,2022-01-02 05:55:46.238257,67,False,Indianapolis,IN
4,EVT00000005,LOAD00000003,TRIP00000003,Pickup,FAC00001,2022-01-01 08:00:00.000000,2022-01-01 07:28:02.169634,83,True,Columbus,OH

In [10]:
df.shape

(170820, 11)

In [11]:
df = df[df["event_type"] == "Delivery"]

In [13]:
df.head()

,event_id,load_id,trip_id,event_type,facility_id,scheduled_datetime,actual_datetime,detention_minutes,on_time_flag,location_city,location_state
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,MI
3,EVT00000004,LOAD00000002,TRIP00000002,Delivery,FAC00050,2022-01-02 02:13:26.608430,2022-01-02 05:55:46.238257,67,False,Indianapolis,IN
5,EVT00000006,LOAD00000003,TRIP00000003,Delivery,FAC00022,2022-01-03 04:28:02.169634,2022-01-03 03:05:02.833256,11,True,Portland,OR
7,EVT00000008,LOAD00000004,TRIP00000004,Delivery,FAC00037,2022-01-02 06:38:56.020030,2022-01-02 08:41:06.714927,142,False,Denver,CO
9,EVT00000010,LOAD00000005,TRIP00000005,Delivery,FAC00050,2022-01-02 22:51:35.544202,2022-01-02 22:23:50.185284,236,True,Seattle,WA

In [14]:
df.shape

(85410, 11)

In [16]:
folder = r"C:\Users\kanam\OneDrive\Desktop\jb\data"

loads   = pd.read_csv(os.path.join(folder, "loads.csv"))
routes  = pd.read_csv(os.path.join(folder, "routes.csv"))
trips   = pd.read_csv(os.path.join(folder, "trips.csv"))
drivers = pd.read_csv(os.path.join(folder, "drivers.csv"))

In [17]:
df = df.merge(loads,   on="load_id",   how="left")
df = df.merge(routes,  on="route_id",  how="left")
df = df.merge(trips,   on="trip_id",   how="left")
df = df.merge(drivers, on="driver_id", how="left")

In [19]:
df.shape

(85410, 52)

In [21]:
df.head()

,event_id,load_id_x,trip_id,event_type,facility_id,scheduled_datetime,actual_datetime,detention_minutes,on_time_flag,location_city,...,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,...,Moore,2015-10-04,NaN,DL989817696,TX,1962-05-26,Omaha,Active,A,11.0
1,EVT00000004,LOAD00000002,TRIP00000002,Delivery,FAC00050,2022-01-02 02:13:26.608430,2022-01-02 05:55:46.238257,67,False,Indianapolis,...,Wilson,2017-07-26,NaN,DL193053577,MI,1991-02-04,Dallas,Active,A,3.0
2,EVT00000006,LOAD00000003,TRIP00000003,Delivery,FAC00022,2022-01-03 04:28:02.169634,2022-01-03 03:05:02.833256,11,True,Portland,...,Anderson,2019-07-14,NaN,DL120812641,MN,1970-06-14,Omaha,Active,A,20.0
3,EVT00000008,LOAD00000004,TRIP00000004,Delivery,FAC00037,2022-01-02 06:38:56.020030,2022-01-02 08:41:06.714927,142,False,Denver,...,Martin,2018-10-04,NaN,DL735760237,TX,1994-07-11,Portland,Active,A,21.0
4,EVT00000010,LOAD00000005,TRIP00000005,Delivery,FAC00050,2022-01-02 22:51:35.544202,2022-01-02 22:23:50.185284,236,True,Seattle,...,Davis,2018-03-10,NaN,DL133318206,NC,1995-03-10,Atlanta,Active,A,24.0

In [22]:
print(df.columns.tolist())

['event_id', 'load_id_x', 'trip_id', 'event_type', 'facility_id', 'scheduled_datetime', 'actual_datetime', 'detention_minutes', 'on_time_flag', 'location_city', 'location_state', 'customer_id', 'route_id', 'load_date', 'load_type', 'weight_lbs', 'pieces', 'revenue', 'fuel_surcharge', 'accessorial_charges', 'load_status', 'booking_type', 'origin_city', 'origin_state', 'destination_city', 'destination_state', 'typical_distance_miles', 'base_rate_per_mile', 'fuel_surcharge_rate', 'typical_transit_days', 'load_id_y', 'driver_id', 'truck_id', 'trailer_id', 'dispatch_date', 'actual_distance_miles', 'actual_duration_hours', 'fuel_gallons_used', 'average_mpg', 'idle_time_hours', 'trip_status', 'first_name', 'last_name', 'hire_date', 'termination_date', 'license_number', 'license_state', 'date_of_birth', 'home_terminal', 'employment_status', 'cdl_class', 'years_experience']

In [23]:
cols = [
    "on_time_flag",
    "detention_minutes",
    "weight_lbs",
    "typical_distance_miles",
    "base_rate_per_mile",
    "years_experience"
]
data = df[cols].copy()
data = data.dropna()

In [26]:
data.shape

(83696, 6)

In [27]:
data.head()

,on_time_flag,detention_minutes,weight_lbs,typical_distance_miles,base_rate_per_mile,years_experience
0,True,230,19178,1271,2.33,11.0
1,False,67,27761,519,2.27,3.0
2,True,11,35594,2332,2.69,20.0
3,False,142,33274,673,1.70,21.0
4,True,236,40257,2172,1.77,24.0

In [28]:
path_final = r"C:\Users\kanam\OneDrive\Desktop\jb\data\final_data.csv"
data.to_csv(path_final, index=False)
print("Saved:", path_final)

Saved: C:\Users\kanam\OneDrive\Desktop\jb\data\final_data.csv

In [29]:
path = r"C:\Users\kanam\OneDrive\Desktop\jb\data\final_data.csv"

In [30]:
df = pd.read_csv(path)

In [31]:
df.head()

,on_time_flag,detention_minutes,weight_lbs,typical_distance_miles,base_rate_per_mile,years_experience
0,True,230,19178,1271,2.33,11.0
1,False,67,27761,519,2.27,3.0
2,True,11,35594,2332,2.69,20.0
3,False,142,33274,673,1.70,21.0
4,True,236,40257,2172,1.77,24.0