In [5]:
import os
import pandas as pd

In [2]:
folder = r"C:\Users\kanam\OneDrive\Desktop\jb\data"

In [4]:
print(os.listdir(folder))

['customers.csv', 'DATABASE_SCHEMA.txt', 'delivery_events.csv', 'drivers.csv', 'driver_monthly_metrics.csv', 'facilities.csv', 'fuel_purchases.csv', 'loads.csv', 'maintenance_records.csv', 'routes.csv', 'safety_incidents.csv', 'trailers.csv', 'trips.csv', 'trucks.csv', 'truck_utilization_metrics.csv']

# loaded Customers.csv

In [6]:
path = r"C:\Users\kanam\OneDrive\Desktop\jb\data\customers.csv"

In [8]:
df = pd.read_csv(path)
df.head()

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564

# loading deliveryevents.csv

In [9]:
path2 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\delivery_events.csv"

In [11]:
df = pd.read_csv(path2)

In [12]:
df.head()

,event_id,load_id,trip_id,event_type,facility_id,scheduled_datetime,actual_datetime,detention_minutes,on_time_flag,location_city,location_state
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55.918185,0,False,Houston,TX
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,MI
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26.608430,62,True,Kansas City,MO
3,EVT00000004,LOAD00000002,TRIP00000002,Delivery,FAC00050,2022-01-02 02:13:26.608430,2022-01-02 05:55:46.238257,67,False,Indianapolis,IN
4,EVT00000005,LOAD00000003,TRIP00000003,Pickup,FAC00001,2022-01-01 08:00:00.000000,2022-01-01 07:28:02.169634,83,True,Columbus,OH

# loading driver_monthly_metrics.csv

In [13]:
path3 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\driver_monthly_metrics.csv"
df = pd.read_csv(path3)
df.head()

,driver_id,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,2022-01-01,26,36620,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,2022-02-01,9,13515,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,2022-03-01,20,30361,62399.62,6.36,4792.2,0.550,7.5
3,DRV00001,2022-04-01,19,28127,68161.13,6.61,4251.4,0.474,8.4
4,DRV00001,2022-05-01,14,16071,36256.82,6.35,2573.1,0.214,6.8

# laoded drivers.csv

In [14]:
path3 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\drivers.csv"
df = pd.read_csv(path3)
df.head()

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

# loaded facilities

In [15]:
path4 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\facilities.csv"
df = pd.read_csv(path4)
df.head()

,facility_id,facility_name,facility_type,city,state,latitude,longitude,dock_doors,operating_hours
0,FAC00001,Houston Distribution Center,Cross-Dock,Houston,TX,29.7604,-95.3698,125,24/7
1,FAC00002,Kansas City Hub,Cross-Dock,Kansas City,MO,39.0997,-94.5786,33,7AM-7PM
2,FAC00003,Charlotte Distribution Center,Distribution Center,Charlotte,NC,35.2271,-80.8431,138,24/7
3,FAC00004,Chicago Distribution Center,Distribution Center,Chicago,IL,41.8781,-87.6298,38,8AM-5PM
4,FAC00005,Indianapolis Hub,Distribution Center,Indianapolis,IN,39.7684,-86.1581,56,8AM-5PM

# loaded fuel_purchses

In [16]:
path5 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\fuel_purchases.csv"
df = pd.read_csv(path5)
df.head()

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
0,FUEL00000001,TRIP00051284,TRK00045,DRV00102,2023-10-22 05:00:00,Columbus,MN,131.6,3.399,447.31,FC567161
1,FUEL00000002,TRIP00073723,TRK00013,NaN,2024-08-04 08:00:00,New York,AZ,139.9,3.180,444.88,FC717910
2,FUEL00000003,TRIP00018286,TRK00024,DRV00142,2022-08-23 13:00:00,Seattle,NE,189.3,3.804,720.10,FC912816
3,FUEL00000004,TRIP00008465,TRK00018,DRV00047,2022-04-20 00:00:00,Memphis,NY,130.7,3.579,467.78,FC776357
4,FUEL00000005,TRIP00069700,TRK00054,NaN,2024-06-13 09:00:00,Columbus,AZ,185.3,3.422,634.10,FC391024

# loaded loads.csv

In [17]:
path6 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\loads.csv"
df = pd.read_csv(path6)
df.head()

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
0,LOAD00000001,CUST00183,RTE00019,2022-01-01,Dry Van,19178,13,3045.23,406.72,100,Completed,Spot
1,LOAD00000002,CUST00076,RTE00058,2022-01-01,Dry Van,27761,22,1224.48,98.61,0,Completed,Dedicated
2,LOAD00000003,CUST00027,RTE00048,2022-01-01,Refrigerated,35594,16,7171.12,792.88,0,Completed,Spot
3,LOAD00000004,CUST00088,RTE00013,2022-01-01,Refrigerated,33274,10,1308.20,141.33,50,Completed,Spot
4,LOAD00000005,CUST00185,RTE00020,2022-01-01,Dry Van,40257,10,3317.18,738.48,0,Completed,Spot

# loaded maintenance_records.csv

In [18]:
path7 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\maintenance_records.csv"
df = pd.read_csv(path7)
df.head()

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
0,MAINT00000001,TRK00085,2022-01-01,Inspection,400255,7.8,781.42,10.41,791.83,Kansas City,22.2,Emergency Inspection
1,MAINT00000002,TRK00041,2022-01-01,Tire,268041,0.9,80.91,3207.16,3288.07,Seattle,8.0,Scheduled Tire
2,MAINT00000003,TRK00090,2022-01-01,Preventive,698915,7.2,733.18,1570.57,2303.75,Miami,16.5,Routine Preventive
3,MAINT00000004,TRK00056,2022-01-02,Inspection,416522,2.8,298.80,67.48,366.28,Kansas City,34.6,Emergency Inspection
4,MAINT00000005,TRK00029,2022-01-02,Repair,179968,4.6,409.08,982.59,1391.67,Omaha,4.4,Emergency Repair

# loaded routes.csv

In [19]:
path8 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\routes.csv"
df = pd.read_csv(path8)
df.head()

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
0,RTE00001,Atlanta,GA,Chicago,IL,677,1.70,0.19,1
1,RTE00002,Atlanta,GA,Miami,FL,697,2.08,0.22,1
2,RTE00003,Chicago,IL,Los Angeles,CA,2003,2.55,0.29,3
3,RTE00004,Chicago,IL,Portland,OR,2017,1.84,0.19,3
4,RTE00005,Chicago,IL,Las Vegas,NV,1749,2.41,0.26,3

# loaded safety_incidents.csv

In [ ]:
path9 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\safety_incidents.csv"
df = pd.read_csv(path9)
df.head()

,incident_id,trip_id,truck_id,driver_id,incident_date,incident_type,location_city,location_state,at_fault_flag,injury_flag,vehicle_damage_cost,cargo_damage_cost,claim_amount,preventable_flag,description
0,INC00000001,TRIP00036079,TRK00006,DRV00006,2023-04-09 14:00:00,Moving Violation,Columbus,PA,True,False,12629.26,0.00,12629.26,True,Severe incident involving equipment
1,INC00000002,TRIP00032462,TRK00084,DRV00006,2023-02-19 11:00:00,Moving Violation,Columbus,NC,False,False,2700.70,14284.24,16984.94,False,Severe incident involving weather
2,INC00000003,TRIP00067583,TRK00106,DRV00119,2024-05-20 01:00:00,Customer Complaint,Seattle,OK,True,False,24302.32,0.00,24302.32,True,Minor incident involving traffic
3,INC00000004,TRIP00049128,TRK00085,DRV00134,2023-09-26 03:00:00,Equipment Damage,Kansas City,TN,True,False,4879.13,0.00,4879.13,True,Moderate incident involving equipment
4,INC00000005,TRIP00062884,TRK00014,DRV00133,2024-03-20 14:00:00,DOT Violation,Las Vegas,IN,False,False,14951.40,0.00,14951.40,False,Minor incident involving other driver

# loaded trailers.csv

In [21]:
path9 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\trailers.csv"
df = pd.read_csv(path9)
df.head()

,trailer_id,trailer_number,trailer_type,length_feet,model_year,vin,acquisition_date,status,current_location
0,TRL00001,4290,Refrigerated,53,2016,1AV889081755621178,2018-05-11,Active,Kansas City
1,TRL00002,8848,Dry Van,53,2018,1BU942062588832828,2018-11-24,Active,Kansas City
2,TRL00003,6147,Dry Van,53,2022,1AV669057807416326,2019-01-28,Active,Milwaukee
3,TRL00004,3910,Dry Van,53,2024,1AV544000060905105,2018-08-27,Active,New York
4,TRL00005,7524,Dry Van,53,2016,1AV170126369813275,2019-11-22,Active,Las Vegas

# loaded truck_utilization_metrics.csv

In [22]:
path10 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\truck_utilization_metrics.csv"
df = pd.read_csv(path9)
df.head()

,trailer_id,trailer_number,trailer_type,length_feet,model_year,vin,acquisition_date,status,current_location
0,TRL00001,4290,Refrigerated,53,2016,1AV889081755621178,2018-05-11,Active,Kansas City
1,TRL00002,8848,Dry Van,53,2018,1BU942062588832828,2018-11-24,Active,Kansas City
2,TRL00003,6147,Dry Van,53,2022,1AV669057807416326,2019-01-28,Active,Milwaukee
3,TRL00004,3910,Dry Van,53,2024,1AV544000060905105,2018-08-27,Active,New York
4,TRL00005,7524,Dry Van,53,2016,1AV170126369813275,2019-11-22,Active,Las Vegas

# loaded trucks.csv

In [23]:
path10 = r"C:\Users\kanam\OneDrive\Desktop\jb\data\trucks.csv"
df = pd.read_csv(path9)
df.head()

,trailer_id,trailer_number,trailer_type,length_feet,model_year,vin,acquisition_date,status,current_location
0,TRL00001,4290,Refrigerated,53,2016,1AV889081755621178,2018-05-11,Active,Kansas City
1,TRL00002,8848,Dry Van,53,2018,1BU942062588832828,2018-11-24,Active,Kansas City
2,TRL00003,6147,Dry Van,53,2022,1AV669057807416326,2019-01-28,Active,Milwaukee
3,TRL00004,3910,Dry Van,53,2024,1AV544000060905105,2018-08-27,Active,New York
4,TRL00005,7524,Dry Van,53,2016,1AV170126369813275,2019-11-22,Active,Las Vegas